#The time is easy to set. When setting the time, its how many hours, minutes and/or seconds
#you want the reboot to happen after either the plugin is reloaded, or loaded into server.
#IE the defaults would mean, once server starts or plugin is reloaded. After that time
#in 10 hours 10 minutes and 10 seconds it would shutdown.

hours: 10
minutes: 10
seconds: 10
