name: HubReboot
version: 2.0
main: hubreboot.HubReboot
description: Hub Reboot Plugin


commands:
  hubsettime: sets the restart time
  
  hubtime2: test command

  hubtime: shows the configured restart time
 
  hubreload: reloads the configuration file